--- #################### 注册中心 + 配置中心相关配置 ####################

spring:
  cloud:
    nacos:
      discovery: # 【配置中心】配置项
        namespace: 6ace76b7-6dd7-4d4b-b75d-737aca2e24a7 # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        username: nacos # Nacos 账号
        password: nacos # Nacos 密码

      config: # 【注册中心】配置项
        namespace: 6ace76b7-6dd7-4d4b-b75d-737aca2e24a7 # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        server-addr: ${spring.cloud.nacos.discovery.server-addr} # Nacos 服务器地址
        username: nacos # Nacos 账号
        password: nacos # Nacos 密码

        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
